config/routes.rb
Cobra::Application.routes.draw do
  root :to => 'contacts#new'
  get 'contacts/stats'
  resources :users, :user_sessions, :contacts, :topics
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    has_and_belongs_to_many :topics
    
    validates_presence_of :date, :on => :create, :message => "(A date is required.)"
    validates_presence_of :staff, :on => :create, :message => "(A staff memeber is required.)"
    validates_presence_of :parentcom, :on => :create, :message => "(Please select a type of parent communication.)"
    #validates_presence_of :topic, :on => :create, :message => "(Please select a topic.)"
    

end

app/models/contacts_topics.rb
class ContactsTopics < ActiveRecord::Base

end

app/models/topic.rb
class Topic < ActiveRecord::Base
    validates_presence_of :topic, :on => :create, :message => "can't be blank"
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  validates_presence_of :first_name, :on => :create, :message => "..You have a first name don't you?"
  validates_presence_of :last_name, :on => :create, :message => "..You have a last name don't you?"
  validates_presence_of :username, :on => :create, :message => "can't be blank"
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  
  def persisted?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  
  private
  
  def require_user
    unless current_user
      flash[:notice] = "You must be logged in to access this page"
      redirect_to new_user_session_url
      return false
    end
  end
  
  def admin_user
      unless current_user.accesslevel == '1'
        flash[:notice] = "You are unauthorize to access the page"
        redirect_to new_contact_url
        return false
      end
  end
  
  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end
  
  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.record
  end 
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_filter :require_user
  before_filter :admin_user, :only => [:index, :show, :edit, :update, :destroy, :stats]

  def index
    @contacts = Contact.order("date DESC")
  end


  def show
    @contact = Contact.find(params[:id])
  end

  def new
    @contact = Contact.new
    @staff = current_user.first_name + " " + current_user.last_name
    @date = Time.now.utc
  end

  def edit
    @contact = Contact.find(params[:id])    
    @staff = current_user.first_name + " " + current_user.last_name
    @date = @contact.date.utc
  end

  def create
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save
        format.html { redirect_to :action => 'new' }
        flash[:notice] = "Contact successfully created."
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    params[:contact][:topic_ids] ||= []
    @contact = Contact.find(params[:id])
    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to(@contact, :notice => 'Contact was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to(contacts_url) }
      format.js { render :nothing => true }
    end
  end
  
  def stats
    @contacts = Contact.all
    @contacts_by_user = Contact.count(:all, :group => 'staff')
    
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :admin_user
  before_filter :require_user
  # GET /topics
  # GET /topics.xml
  def index
    @topics = Topic.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.xml
  def show
    @topic = Topic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.xml
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.xml
  def create
    @topic = Topic.new(params[:topic])

    respond_to do |format|
      if @topic.save
        format.html { redirect_to(topics_url, :notice => 'Topic was successfully created.') }
        format.xml  { render :xml => @topic, :status => :created, :location => @topic }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @topic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.xml
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to(@topic, :notice => 'Topic was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @topic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.xml
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to(topics_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  def new
    @user_session = UserSession.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def create
    @user_session = UserSession.new(params[:user_session])

    respond_to do |format|
      if @user_session.save
        format.html { redirect_to(:contacts, :notice => 'Login Successful') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def destroy
    @user_session = UserSession.find
    @user_session.destroy

    respond_to do |format|
      format.html { redirect_to(root_url, :notice => 'Goodbye!') }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :admin_user,  :only => [:index]

  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(:users, :notice => 'Registration Successful') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(:controller => 'contacts', :action => 'new') }
        flash[:notice] = "Successfully updated you user account."
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<div class="standard-form">
<%= form_for(@contact) do |f| %>
	<%= f.error_messages %>
<br />
  <div class="field">
    <%= f.label :date, :class =>'main' %><br />
    <%= f.text_field :date, :class => 'textbox', :value => @date %>
  </div>
  <div class="field">
    <%= f.label :staff, 'Staff responding', :class =>'main' %><br />
    <%= f.text_field :staff, :value => @staff, :class => 'textbox'  %>
  </div>
  <div class="field">
	<% @parentcom_opt = options_for_select([['Parents Assistance Line', 'Parents Assistance Line'], ['Email (scparents@sc.edu)', 'Email (scparents@sc.edu)'], ['Direct Phone Call', 'Direct Phone Call'], ['In-person visit', 'In-person visit'], ['Other', 'Other']]) %>
    <%= f.label :parentcom,'Type of parent communication', :class =>'main' %><br />
    <%= f.select(:parentcom, @parentcom_opt, {:prompt => 'Please choose one'}) %>
  </div>
  <div class="field">
    <%= f.label :parentcomother, 'If none of the above, other type of parent communication', :class =>'main' %><br />
    <%= f.text_field :parentcomother, :class => 'textbox' %>
  </div>
  <div class="field">
	<%= f.label :topic,'Topic(s)', :class =>'main' %><br />
	
	<% for topic in Topic.order("topic ASC") %>
	<div class="topic">
	    <%= check_box_tag "contact[topic_ids][]", topic.id, @contact.topics.include?(topic) %>
		<div class=""><%= topic.topic.humanize %></div>
		<div class="checkhelp"><%= topic.checkhelp.humanize %></div>
	</div>
	<% end %>
  </div>
  <div class="spacer"></div>
  <div class="field">
    <%= f.label :topic_other, 'Other Topic (if not listed)', :class =>'main' %><br />
    <%= f.text_field :topic_other, :class => 'textbox' %>
  </div>
  <div class="field">
    <%= f.label :comment,'Comments or follow up needed', :class =>'main' %><br />
    <%= f.text_area :comment, :class => 'textarea' %>
  </div>
  <div class="field">
    <%= f.label :feedback,'Feedback given to', :class =>'main' %><br />
    <%= f.text_field :feedback, :class => 'textbox' %>
  </div>
  <div class="field">
    <%= f.submit @contactbtn, :id => 'emphasis', :class => 'btn' %>
  </div>
<% end %>
</div>

app/views/contacts/_topicsloop.html.erb
<% contact.topics.each do |topic|%>
	<%= topic.topic%><br />
<% end %> 

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h2>Dashboard</h2>
<table class="standard-table" id="dashboard" width="940px" border="0" cellpadding="0" cellspacing="0">
	<thead>
	  <tr>
	    <th>Date</th>
	    <th>Staff Responding</th>
	    <th>Parent Communication</th>
	    <th>Topic</th>
	    <th>Comments</th>
	    <th>Feedback given to</th>
	    <th></th>
	  </tr>
	</thead>
	<tbody>
	<% @contacts.each do |contact| %>
	  <tr>
	    <td>
			
			<% if !contact.created_at.nil? && contact.created_at.to_date == Date.today %>
				<%= image_tag('today.png', :class => 'todayicn') %>
			<% end %>
			<%= contact.date.strftime('%m/%d/%Y at %I:%M%p') %>
		</td>
	    <td><%= contact.staff %></td>
	    <td><%= contact.parentcom %> <%= contact.parentcomother %></td>
	    <td>
			<% if !contact.topic.presence %>
				<% contact.topics.each do |topic|%>
					<%= topic.topic%><br />
				<% end %>
			<% else %>
				<%= contact.topic %>
			<% end %>	 
			<%= contact.topic_other %>
		</td>
	    <td><%= contact.comment %></td>
	    <td><%= contact.feedback %></td>
	    <td>
			<%= link_to image_tag('lens.gif'), contact %>
	    	<%= link_to image_tag('edit.png'), edit_contact_path(contact) %>
	    	<%= link_to image_tag('delete.gif'), contact, :confirm => 'Are you sure?', :method => :delete, :remote =>true, :class => 'delete_contact' %>
		</td>
	  </tr>
	<% end %>
	</tbody>
</table>
<br />
<div class="spacer"></div>

app/views/contacts/new.html.erb
<h2>New contact</h2>

<%= render 'form' %>

app/views/contacts/show.html.erb
<h2><%= @contact.date.strftime('%m/%d/%Y at %I:%M%p') %></h2>
<p id="notice"><%= notice %></p>

<p>
	<b>Staff Responding</b><br />
  	<%= @contact.staff %>
</p>
<br />
<p>
  	<b>Type of parent communication</b><br />
  	<%= @contact.parentcom %><%= @contact.parentcomother %>
</p>
<br />
<p>
  	<b>Topic(s)</b><br />
	<% @contact.topics.each do |topic|%>
		<%= topic.topic%><br />
	<% end %>	 
	<%= @contact.topic_other %>
</p>
<br />
<p>
  	<b>Comments</b><br />
  	<%= @contact.comment %>
</p>
<br />
<p>
	<b>Feedback given to</b><br />
  	<%= @contact.feedback %>
</p>
<br />

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/stats.html.erb
<h1>Stats</h1>

<h4>Contacts by user</h4>

	<%= @contacts_by_user %>


<br />
By type of parent communication

By topic

By date month

By date semester

<h4>Total number of contacts</h4>
----> <%= @contacts.count %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Parents Tracking</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>
</head>
<body>
	<div class="wrapper">
		<div class="header">
			<%= image_tag('logo.png') %>	
			<div class="header-controls">
				<ul>
				<% if current_user %>
					<li class="first">S'ak Passe <%= current_user.username %> </li>  
					<li><%= link_to "Account", edit_user_path(current_user.id)%></li>
					<li><%= link_to "Logout", :logout%>	</li>	
				<% end %>
				</ul>	
			</div>
		</div>
		<% if current_user && current_user.accesslevel == '1' %>
		<div class="primary-navigation">
			<ul>
				<li class="active"><%= link_to 'Dashboard', contacts_path %></li>
				<li><%= link_to 'New Contact', new_contact_path %></li>
				<li><%= link_to 'Manage Users', users_path %></li>
				<li><%= link_to 'Manage Topics', topics_path %></li>
				<li><% link_to 'Reports', '/contacts/stats' %></li>
			</ul>	
		<div class="clear-both"></div>
		</div>
		<% end %>
		<% if flash[:alert] %>	
			<p class="flash flash-error"><%= notice %></p>
		<% end %>
		<% if flash[:notice] %>	
			<p class="flash flash-success"><%= notice %></p>
		<% end %>	
		<div class="standard-block">	
			<%= yield %>
		</div>
		<div class="spacer"></div>
		<div class="footer">
        	<%= image_tag('footer_logo.png') %>
		</div>
	</div>
</body>
</html>

app/views/topics/_form.html.erb
<div class="standard-form">
<%= form_for(@topic) do |f| %>
<p class="flash flash-error"><%= f.error_messages %></p>
<br />
  <div class="field">
    <%= f.label :topic, :class =>'main' %><br />
    <%= f.text_field :topic, :class => 'textbox' %>
  </div>
  <div class="field">
    <%= f.label :checkhelp, 'Description', :class =>'main' %><br />
    <%= f.text_area :checkhelp, :class => 'textarea' %>
  </div>
  <div class="field">
    <%= f.submit @topicbtn, :class => 'btn', :id => 'emphasis'  %>
  </div>
<% end %>
</div>

app/views/topics/edit.html.erb
<h2>Edit topic</h2>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h2>Topics</h2>
<%= link_to 'New Topic', new_topic_path %>
<div class="spacer"></div>
<table class="standard-table" id="topicTable" width="940px" border="0" cellpadding="0" cellspacing="0">
	<thead>
	  <tr>
	    <th>Topic</th>
	    <th>Description</th>
	    <th></th>
	  </tr>
	</thead>
	<tbody>
	<% @topics.each do |topic| %>
	  <tr>
	    <td><%= topic.topic %></td>
	    <td><%= topic.checkhelp %></td>
	    <td>
			<%= link_to image_tag('edit.png'), edit_topic_path(topic) %>
			<%= link_to image_tag('delete.gif'), topic, :confirm => 'Are you sure?', :method => :delete %>
		</td>
	  </tr>
	<% end %>
	</tbody>
</table>
<div class="spacer"></div>

app/views/topics/new.html.erb
<h2>New topic</h2>
<div class="spacer"></div>
<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Topic:</b>
  <%= @topic.topic %>
</p>

<p>
  <b>Checkhelp:</b>
  <%= @topic.checkhelp %>
</p>


<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>

app/views/user_sessions/_form.html.erb
<div class="standard-form">	
<%= form_for(@user_session) do |f| %>
<%= f.error_messages %>
<br />
<fieldset>
	<legend>Login</legend>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username, :class => 'textbox' %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, :class => 'textbox' %>
  </div>
  <div class="field">
    <%= f.submit 'Login', :class => 'btn', :id => 'emphasis' %>
  </div>
</fieldset>
<% end %>
</div>

app/views/user_sessions/edit.html.erb
<h1>Editing user_session</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_session %> |
<%= link_to 'Back', user_sessions_path %>

app/views/user_sessions/index.html.erb
<h1>Listing user_sessions</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_sessions.each do |user_session| %>
  <tr>
    <td><%= user_session.username %></td>
    <td><%= user_session.password %></td>
    <td><%= link_to 'Show', user_session %></td>
    <td><%= link_to 'Edit', edit_user_session_path(user_session) %></td>
    <td><%= link_to 'Destroy', user_session, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User session', new_user_session_path %>

app/views/user_sessions/new.html.erb
<h2>Login</h2>
<%= render 'form' %>

app/views/user_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user_session.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user_session.password %>
</p>


<%= link_to 'Edit', edit_user_session_path(@user_session) %> |
<%= link_to 'Back', user_sessions_path %>

app/views/users/_form.html.erb
<div class="spacer"></div>
<div class="standard-form">
<%= form_for(@user) do |f| %>
<%= f.error_messages%>
<br />
  <div class="field">
    <%= f.label :first_name, :class =>'main' %><br />
    <%= f.text_field :first_name, :class =>'textbox' %>
  </div>
  <div class="field">
    <%= f.label :last_name, :class =>'main' %><br />
    <%= f.text_field :last_name, :class =>'textbox' %>
  </div>
  <div class="field">
    <%= f.label :office_number, :class =>'main' %><br />
    <%= f.text_field :office_number, :class =>'textbox' %>
  </div>
  <div class="field">
    <%= f.label :username, :class =>'main' %><br />
    <%= f.text_field :username, :class =>'textbox' %>
  </div>
  <div class="field">
    <%= f.label :email, :class =>'main' %><br />
    <%= f.text_field :email, :class =>'textbox' %>
  </div>
  <div class="field">
	<% if current_user && current_user.accesslevel == '1' %>
	<% @accesslvl = options_for_select([['Admin', '1'], ['User', '0']]) %>
    <%= f.label :accesslevel, :class =>'main' %><br />
    <%= f.select(:accesslevel, @accesslvl, {:prompt => 'Please choose an access level'}) %>
	<% else%>
		<%= f.hidden_field :accesslevel, :value => 0 %>
	<% end %>
  </div>
	
  <div class="field">
    <%= f.label :password, :class =>'main' %><br />
    <%= f.password_field :password, :class =>'textbox' %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, :class =>'main' %><br />
    <%= f.password_field :password_confirmation, :class =>'textbox' %>
  </div>
  <div class="field">
    <%= f.submit @userbtn, :class => 'btn', :id => 'emphasis' %>
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<h2>Edit user</h2>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h2>Users</h2>
<%= link_to 'New User', new_user_path %>
<div class="spacer"></div>
<table class="standard-table" id="userTable" width="940px" border="0" cellpadding="0" cellspacing="0">
	<thead>	
	  <tr>
	    <th>Username</th>
	    <th>Email</th>
		<th>Access Level</th>
	    <th>Login count</th>
	    <th>Last login at</th>
	    <th>Current login at</th>
	    <th></th>
	  </tr>
	</thead>
	<% @users.each do |user| %>
	<tbody>
	  <tr>
	    <td><%= user.username %></td>
	    <td><%= user.email %></td>
		<td><%  if user.accesslevel == '1'  %> Admin <% else %> User <% end %></td>
	    <td><%= user.login_count %></td>
	    <td>
			<% if !user.last_login_at.blank? %>
				<%= user.last_login_at.strftime('%m/%d/%Y at %I:%M%p') %>
			<% end %>	
		</td>	
	    <td><% if !user.current_login_at.blank? %>
				<%= user.current_login_at.strftime('%m/%d/%Y at %I:%M%p') %>
			<% end %>
		</td>
	    <td><%= link_to image_tag('lens.gif'), user %>
	    <%= link_to image_tag('edit.png'), edit_user_path(user) %>
	    <%= link_to image_tag('delete.gif'), user, :confirm => 'Are you sure?', :method => :delete %></td>
	  </tr>
	</tbody>
	<% end %>
</table>

<br />
<div class="spacer"></div>

app/views/users/new.html.erb
<h1>Register new user</h1>
<% @userbtn = 'Register User' %>
<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h2>Showing <%= @user.username %></h2>
<p id="notice"><%= notice %></p>

<p>
  <b>Email</b><br />
  <%= @user.email %>
</p>
<br />
<p>
  <b>Login count</b><br />
  <%= @user.login_count %>
</p>
<br />
<p>
  <b>Failed login count</b><br />
  <%= @user.failed_login_count %>
</p>
<br />
<p>
  <b>Last login at</b><br />
  <%= @user.last_login_at %>
</p>
<br />
<p>
  <b>Current login at</b><br />
  <%= @user.current_login_at %>
</p>
<br />
<p>
  <b>Current login ip</b><br />
  <%= @user.current_login_ip %>
</p>
<br />
<p>
  <b>Last login ip</b><br />
  <%= @user.last_login_ip %>
</p>
<br />
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>